person:
  name: zhangsan
  age: 18

#DB Configuration:
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.41.100:3306/ssm?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

#spring集成Mybatis环境
#pojo别名扫描包
mybatis:
  type-aliases-package: com.xiaoa.domain
#加载Mybatis映射文件
  mapper-locations: classpath:mapper/*Mapper.xml